### ISSUE TITLE
Can't build on Archlinux

### ISSUE THREAD

**Issue by asakura42** [team-pp-studio/VoiceTuber#9]
After doing `conan install ./ --build missing -s build_type=Release` I ran `cmake --build --preset conan-release` as you write but it outputs `Error: could not load cache`. I'm very bad in cpp building things so maybe you can check what may be wrong?

**Comment by mika314** [comment]
Did you try secondary instruction with the `coddle` command?

**Comment by StellaSmith** [comment]
Could you post the complete logs and the conan version you're using?

**Comment by StellaSmith** [comment]
It seems a build step was missing, #11 should fix this.
@asakura42  please confirm the changes on the pull request work for you.
